apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  credentials: |-
    [default]
    aws_access_key_id = {{ required "A valid credentials is required!" .Values.secret.creds.awsAccessKeyId }}}
    aws_secret_access_key = {{ required "A valid credentials is required!" .Values.secret.creds.awsSecretAccessKey }}
# data:
#   credentials: {{ .Values.secret.creds.base64Encoded }}