providerConfig:
  name: aws-provider
  
secret:    
  name: aws-creds
  key: credentials
  creds:
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
    # base64Encoded: |-
    #   [default]
    #   aws_access_key_id = ""
    #   aws_secret_access_key = ""
